version: 2.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.12.0-stretch-browsers-legacy

filter_only_staging: &filter_only_staging
  filters:
    branches:
      only: staging

filter_only_production: &filter_only_production
  filters:
    branches:
      only: production

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - restore_cache:
          keys:
            # lock ファイルが変更されると、より広範囲にマッチする 2 番目以降のパターンがキャッシュの復元に使われます
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run: yarn install
      - run: yarn add --dev firebase-tools
      - run: ln -s ./node_modules/.bin/firebase .
      - run: cd functions && npm install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          name: Save npm Package Cache
          paths:
            - ./functions/node_modules # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./*

  # test:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/repo
  #     - run: yarn test

  build-stg:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn generate
      - persist_to_workspace:
          root: ~/repo
          paths:
            - functions/public

  build-prod:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn generate:prod
      - persist_to_workspace:
          root: ~/repo
          paths:
            - functions/public

  deploy-stg:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: ./firebase use stg
      - run: ./firebase functions:config:set basic.auth.user="$BASIC_AUTH_USER" basic.auth.pass="$BASIC_AUTH_PASS"
      - run: ./firebase deploy --token "$FIREBASE_STG_TOKEN"

  deploy-prod:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: ./firebase use prod
      - run: ./firebase deploy --token "$FIREBASE_TOKEN" --only firestore,storage,hosting

workflows:
  version: 2.1
  test-deploy:
    jobs:
      - setup
      # - test:
      #     requires:
      #       - setup
      - build-stg:
          <<: *filter_only_staging
          requires:
            - setup
            # - test
      - build-prod:
          <<: *filter_only_production
          requires:
            - setup
            # - test
      - deploy-stg:
          <<: *filter_only_staging
          requires:
            - setup
            # - test
            - build-stg
      - deploy-prod:
          <<: *filter_only_production
          requires:
            - setup
            # - test
            - build-prod
