version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.12.0-stretch-browsers-legacy

filter_only_staging: &filter_only_staging
  filters:
    branches:
      only: staging

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - run: yarn add --dev firebase-tools
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./*

  # test:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/repo
  #     - run: yarn test

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: yarn generate
      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run: ln -s ./node_modules/.bin/firebase .
      - run: ./firebase use stg
      - run: ./firebase deploy --only hosting --project "$FIREBASE_STG_PROJECT_ID" --token "$FIREBASE_STG_TOKEN"

workflows:
  version: 2
  test-deploy:
    jobs:
      - setup
      # - test:
      #     requires:
      #       - setup
      - build:
          <<: *filter_only_staging
          requires:
            - setup
            # - test
      - deploy:
          <<: *filter_only_staging
          requires:
            - setup
            # - test
            - build
